name: Automated go mod tidy

on:
  issue_comment:
    types:
      - created
  push:
    branches:
      - main
    paths:
      - go.mod
      - go.sum
  schedule:
    - cron: 48 4 * * *
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  go-mod-tidy:
    name: go mod tidy

    runs-on: ubuntu-24.04
    environment: automated

    if: github.event_name != 'issue_comment' || (startsWith(github.event.issue.title, 'Automated go mod tidy') && contains(github.event.comment.body,
      '/rerun'))
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Go mod tidy
        run: |
          go mod tidy -v 2>&1 | tee .github/update.log
          sed -e 's/\x1b\[[0-9;]*m//g' -e 's/^go: /- /' .github/update.log | grep -v "^- downloading " > .github/pr_body.log || true

      - name: Check for changes
        run: |
          if git diff --exit-code; then
            echo "changes=false" >> $GITHUB_ENV
          else
            echo "changes=true" >> $GITHUB_ENV
          fi

      - name: Commit and push to branch
        if: env.changes == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          default_author: github_actions
          message: Automated go mod tidy
          new_branch: automated/go-mod-tidy
          fetch: false
          push: origin automated/go-mod-tidy --set-upstream --force

      - name: Create pull request
        if: env.changes == 'true'
        run: |-
          if [[ $(gh pr view automated/go-mod-tidy --json state --jq .state || true) != "OPEN" ]]; then
            gh pr create \
              --head automated/go-mod-tidy \
              --title "Automated go mod tidy" \
              --body-file .github/pr_body.log \
              --label automated
          else
            gh pr edit automated/go-mod-tidy \
              --title "Automated go mod tidy" \
              --body-file .github/pr_body.log
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Close pull request
        if: env.changes == 'false'
        run: gh pr list --head automated/go-mod-tidy --json number --jq '.[].number' | xargs -rn1 gh pr close --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
